import{a as f,S as h,i as u}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const l of e.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function s(t){if(t.ep)return;t.ep=!0;const e=a(t);fetch(t.href,e)}})();async function b(o,r=1,a=40){const s={params:{key:"48866244-bc210103fc5496976cb537971",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}},t=`https://pixabay.com/api/?key=${s.params.key}&q=${s.params.q}&image_type=${s.params.image_type}&orientation=${s.params.orientation}&safesearch=${s.params.safesearch}&page=${r}&per_page=${a}`;return f.get(t)}async function w(o,r){const a=document.querySelector(r);a.innerHTML="",await new Promise(e=>setTimeout(e,0));const s=o.map(e=>`<li class="gallery-item">
        <a class='gallery-link' href="${e.largeImageURL}">
          <img class="li-img" src="${e.webformatURL}" alt="${e.tags}" />
          <div class="li-text">
            <table class="table">
              <tr><td>Likes</td><td>Views</td><td>Comment</td><td>Downloads</td></tr>
              <tr><td>${e.likes}</td><td>${e.views}</td><td>${e.comments}</td><td>${e.downloads}</td></tr>
            </table>
          </div>
        </a>
      </li>`).join("");a.insertAdjacentHTML("afterbegin",s);const t=new h(r+" a",{captionsData:"alt",captionDelay:250,close:!0});await new Promise(e=>setTimeout(e,0)),t.refresh(),a.addEventListener("click",e=>{e.target.tagName==="IMG"&&t.close()})}const S=document.querySelector("#search-form"),$=document.querySelector("#search-input"),L=document.querySelector(".gallery"),c=document.querySelector("#loading-message"),n=document.querySelector("#load-more"),p=document.querySelector("#end-message");let g="",i=1;const m=40;let d=0;S.addEventListener("submit",async function(o){if(o.preventDefault(),g=$.value.trim(),!g){u.show({backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"rgba(255, 255, 255, 1)",close:!0,position:"topRight",title:"Error",titleColor:"#fff",titleSize:"16px",message:"Input search string"});return}L.innerHTML="",i=1,n.style.display="none",p.style.display="none",await y()});async function y(){c.style.display="block";try{const o=await b(g,i,m);if(c.style.display="none",o.data.hits.length===0){u.show({backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"rgba(255, 255, 255, 1)",close:!0,position:"topRight",title:"Error",titleColor:"#fff",titleSize:"16px",message:"Sorry, there are no images matching your search query. Please try again"});return}d=o.data.totalHits,console.log(`Total images available: ${d}`),console.log(`Images received: ${o.data.hits.length}`),w(o.data.hits,".gallery",!0),i+=1,(i-1)*m>=d?(n.style.display="none",p.style.display="block"):n.style.display="block",q()}catch(o){c.style.display="none",console.error(o),u.show({backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"rgba(255, 255, 255, 1)",close:!0,position:"topRight",title:"Error",titleColor:"#fff",titleSize:"16px",message:"Sorry, there was an error fetching images. Please try again."})}}n.addEventListener("click",async function(){await y()});function q(){const o=document.querySelector(".gallery img");if(o){const r=o.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
