import{a as h,S as b,i}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const p of s.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&a(p)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();async function y(t,r=1,o=40){const a={params:{key:"48866244-bc210103fc5496976cb537971",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}},e=`https://pixabay.com/api/?key=${a.params.key}&q=${a.params.q}&image_type=${a.params.image_type}&orientation=${a.params.orientation}&safesearch=${a.params.safesearch}&page=${r}&per_page=${o}`;return h.get(e)}const S=new b(".gallery a",{captionsData:"alt",captionDelay:250}),w=document.querySelector(".gallery");async function f(t){const r=t.map(o=>`<li class="gallery-item">
        <a class='gallery-link' href="${o.largeImageURL}">
          <img class="li-img" src="${o.webformatURL}" alt="${o.tags}" />
          <div class="li-text">
            <table class="table">
              <tr><td>Likes</td><td>Views</td><td>Comment</td><td>Downloads</td></tr>
              <tr><td>${o.likes}</td><td>${o.views}</td><td>${o.comments}</td><td>${o.downloads}</td></tr>
            </table>
          </div>
        </a>
      </li>`).join("");w.insertAdjacentHTML("afterbegin",r),S.refresh()}const $=document.querySelector("#search-form"),m=document.querySelector("#search-input"),v=document.querySelector(".gallery"),d=document.querySelector("#loading-message"),g=document.querySelector("#load-more");document.querySelector("#end-message");let c="",l=1;const u=40;let n=0;$.addEventListener("submit",async function(t){if(t.preventDefault(),c=m.value.trim(),!c){i.show({backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"rgba(255, 255, 255, 1)",close:!0,position:"topRight",title:"Error",titleColor:"#fff",titleSize:"16px",message:"Input search string"});return}v.innerHTML="",l=1,g.style.display="none";const r=await y(c,l,u);d.style.display="none";try{if(r.data.hits.length===0){i.show({backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"rgba(255, 255, 255, 1)",close:!0,position:"topRight",title:"Error",titleColor:"#fff",titleSize:"16px",message:"Sorry, there are no images matching your search query. Please try again"});return}f(r.data.hits),n=r.data.totalHits,m.value="",n>u&&(g.style.display="block")}catch(o){d.style.display="none",console.error(o),i.show({backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"rgba(255, 255, 255, 1)",close:!0,position:"topRight",title:"Error",titleColor:"#fff",titleSize:"16px",message:"Sorry, there was an error fetching images. Please try again."})}});async function C(){d.style.display="block",l+=1;try{const t=await y(c,l,u);n=t.data.totalHits,console.log(`Total images available: ${n}`),console.log(`Images received: ${t.data.hits.length}`),f(t.data.hits),(l-1)*u>=n&&(g.style.display="none",i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results"})),q()}catch(t){d.style.display="none",console.error(t),i.show({backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"rgba(255, 255, 255, 1)",close:!0,position:"topRight",title:"Error",titleColor:"#fff",titleSize:"16px",message:"Sorry, there was an error fetching images. Please try again."})}}g.addEventListener("click",C);function q(){const t=document.querySelector(".gallery img");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
